// <auto-generated />
using System;
using Empleados.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Empleados.Data.Migrations
{
    [DbContext(typeof(EmpleadosDbContext))]
    [Migration("20260715211725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Empleados.Data.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Tecnología de la Información"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Operaciones y Logística"
                        });
                });

            modelBuilder.Entity("Empleados.Data.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTerminacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoRuta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Empleados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Mendoza",
                            CorreoElectronico = "c.mendoza@organizacion.com",
                            DepartamentoId = 2,
                            Direccion = "Calle Principal 123",
                            Estado = 1,
                            FechaContratacion = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1988, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoRuta = "uploads/empleados/default.png",
                            Nombre = "Carlos",
                            Puesto = "Gerente de TI",
                            Salario = 85000.00m,
                            Telefono = "809-555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Gómez",
                            CorreoElectronico = "a.gomez@organizacion.com",
                            DepartamentoId = 1,
                            Direccion = "Av. Central 456",
                            Estado = 1,
                            FechaContratacion = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1992, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoRuta = "uploads/empleados/default.png",
                            Nombre = "Ana",
                            Puesto = "Generalista de RRHH",
                            Salario = 45000.00m,
                            Telefono = "809-555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Rosario",
                            CorreoElectronico = "l.rosario@organizacion.com",
                            DepartamentoId = 3,
                            Direccion = "Calle 4, No. 12",
                            Estado = 1,
                            FechaContratacion = new DateTime(2019, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1990, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoRuta = "uploads/empleados/default.png",
                            Nombre = "Luis",
                            Puesto = "Coordinador de Logística",
                            Salario = 55000.00m,
                            Telefono = "809-555-0103"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Peralta",
                            CorreoElectronico = "m.peralta@organizacion.com",
                            DepartamentoId = 2,
                            Direccion = "Residencial Altagracia B4",
                            Estado = 1,
                            FechaContratacion = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1995, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoRuta = "uploads/empleados/default.png",
                            Nombre = "María",
                            Puesto = "Desarrolladora Fullstack",
                            Salario = 70000.00m,
                            Telefono = "809-555-0104"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Martínez",
                            CorreoElectronico = "j.martinez@organizacion.com",
                            DepartamentoId = 2,
                            Direccion = "Calle Duarte 78",
                            Estado = 1,
                            FechaContratacion = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1997, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoRuta = "uploads/empleados/default.png",
                            Nombre = "José",
                            Puesto = "Soporte Técnico",
                            Salario = 35000.00m,
                            Telefono = "809-555-0105"
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "Castro",
                            CorreoElectronico = "e.castro@organizacion.com",
                            DepartamentoId = 1,
                            Direccion = "Av. Anacaona E12",
                            Estado = 1,
                            FechaContratacion = new DateTime(2015, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1983, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoRuta = "uploads/empleados/default.png",
                            Nombre = "Elena",
                            Puesto = "Directora de RRHH",
                            Salario = 95000.00m,
                            Telefono = "809-555-0106"
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "Santos",
                            CorreoElectronico = "r.santos@organizacion.com",
                            DepartamentoId = 3,
                            Direccion = "Calle Las Carreras 203",
                            Estado = 1,
                            FechaContratacion = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1991, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoRuta = "uploads/empleados/default.png",
                            Nombre = "Ricardo",
                            Puesto = "Supervisor de Despacho",
                            Salario = 48000.00m,
                            Telefono = "809-555-0107"
                        },
                        new
                        {
                            Id = 8,
                            Apellido = "Espinal",
                            CorreoElectronico = "l.espinal@organizacion.com",
                            DepartamentoId = 1,
                            Direccion = "Urb. Real, Calle C",
                            Estado = 1,
                            FechaContratacion = new DateTime(2022, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1994, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoRuta = "uploads/empleados/default.png",
                            Nombre = "Laura",
                            Puesto = "Analista de Reclutamiento",
                            Salario = 40000.00m,
                            Telefono = "809-555-0108"
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "Jiménez",
                            CorreoElectronico = "p.jimenez@organizacion.com",
                            DepartamentoId = 2,
                            Direccion = "Ensanche Luperón No. 5",
                            Estado = 1,
                            FechaContratacion = new DateTime(2018, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1989, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoRuta = "uploads/empleados/default.png",
                            Nombre = "Pedro",
                            Puesto = "Administrador de Sistemas",
                            Salario = 65000.00m,
                            Telefono = "809-555-0109"
                        },
                        new
                        {
                            Id = 10,
                            Apellido = "Vargas",
                            CorreoElectronico = "s.vargas@organizacion.com",
                            DepartamentoId = 3,
                            Direccion = "Villa Consuelo, Calle 3",
                            Estado = 1,
                            FechaContratacion = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1999, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoRuta = "uploads/empleados/default.png",
                            Nombre = "Sofía",
                            Puesto = "Auxiliar de Almacén",
                            Salario = 30000.00m,
                            Telefono = "809-555-0110"
                        });
                });

            modelBuilder.Entity("Empleados.Data.Entities.Empleado", b =>
                {
                    b.HasOne("Empleados.Data.Entities.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Empleados.Data.Entities.Departamento", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
